import { BuildingData, UniversityCampusStats, AlertItem, RoomData } from './types';

export const initialCampusStats: UniversityCampusStats = {
  campusName: 'EnerVerse King Fahd University Campus',
  campusNameAr: 'جامعة إينرفيرس - الحرم الجامعي الذكي',
  totalLoadKw: 2468,
  baselineLoadKw: 2610,
  solarGenerationKw: 742,
  gridImportKw: 1726,
  batteryStoragePct: 78,
  batteryStorageKw: 180,
  co2OffsetTodayKg: 4210,
  dailyConsumptionMwh: 28.4,
  dailyBudgetMwh: 33.0,
  totalBuildingsCount: 14,
  totalMonitoredRooms: 284,
  activeOccupancy: 3840,
  renewableSharePct: 30.1,
  outdoorTempC: 31.8,
  solarIrradianceWm2: 840,
  activeAlertsTotal: 6,
  criticalAlertsCount: 2,
};

const createHourlyTrend = (base: number, peakHours: number[] = [11, 12, 13, 14, 15]): { time: string; actualKw: number; baselineKw: number; solarKw: number }[] => {
  const hours = ['06:00', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00', '20:00', '22:00'];
  return hours.map((time, idx) => {
    const isPeak = idx >= 2 && idx <= 5;
    const factor = isPeak ? 1.35 : 0.85;
    const actual = Math.round(base * factor * (0.95 + Math.random() * 0.1));
    const baseline = Math.round(base * factor * 1.1);
    const solar = idx >= 1 && idx <= 6 ? Math.round(base * 0.35 * Math.sin(((idx - 1) / 5) * Math.PI)) : 0;
    return { time, actualKw: actual, baselineKw: baseline, solarKw: solar };
  });
};

export const initialBuildings: BuildingData[] = [
  {
    id: 'eng-hall',
    code: 'ENG-01',
    name: 'College of Engineering & Technology',
    nameAr: 'كلية الهندسة والتقنية',
    zone: 'North Campus',
    zoneAr: 'المنطقة الشمالية',
    areaSqm: 24500,
    floorsCount: 4,
    occupancyCurrent: 720,
    occupancyMax: 950,
    currentPowerKw: 486,
    baselineKw: 540,
    solarRoofKw: 165,
    status: 'optimal',
    eui: 114,
    hvacMode: 'Eco-Setback',
    hvacModeAr: 'التحكم الذكي التوفيري',
    systemsBreakdown: { hvac: 46, lighting: 18, plugs: 22, specialized: 14 },
    temperatureAvg: 22.8,
    co2PpmAvg: 590,
    activeAlertsCount: 1,
    hourlyTrend: createHourlyTrend(480),
    floors: [
      {
        floorNumber: 1,
        name: 'Ground Floor: Robotics, Mechatronics & Main Lecture Hall',
        nameAr: 'الدور الأرضي: معامل الروبوتات والميكاترونيكس والمدرج الرئيسي',
        powerKw: 154,
        roomsCount: 6,
        rooms: [
          {
            id: 'eng-101',
            code: 'ENG-101',
            name: 'Autonomous Robotics & AI Lab',
            nameAr: 'معمل الروبوتات والذكاء الاصطناعي المستقل',
            type: 'lab',
            floorNumber: 1,
            floorName: 'Ground Floor',
            floorNameAr: 'الدور الأرضي',
            buildingId: 'eng-hall',
            areaSqm: 140,
            powerKw: 18.4,
            baselineKw: 22.0,
            powerBreakdown: { hvac: 7.2, lighting: 2.1, equipment: 8.5, standby: 0.6 },
            telemetry: {
              temperature: 21.8,
              humidity: 46,
              co2Ppm: 540,
              noiseDb: 48,
              lightLux: 480,
              occupancy: 16,
              capacity: 25,
              doorOpen: false,
            },
            controls: {
              thermostatSetpoint: 22.0,
              hvacMode: 'cool',
              fanSpeed: 'auto',
              lightingLevel: 75,
              lightingMode: 'circadian',
              socketPowerCut: false,
              ecoScheduleActive: true,
            },
            historyHourly: [
              { time: '08:00', actualKw: 8.2, baselineKw: 12.0 },
              { time: '10:00', actualKw: 16.5, baselineKw: 19.0 },
              { time: '12:00', actualKw: 19.8, baselineKw: 22.5 },
              { time: '14:00', actualKw: 18.4, baselineKw: 22.0 },
              { time: '16:00', actualKw: 14.1, baselineKw: 17.0 },
              { time: '18:00', actualKw: 6.8, baselineKw: 10.0 },
            ],
          },
          {
            id: 'eng-102',
            code: 'ENG-102',
            name: 'Mechatronics & 3D Fabrication Suite',
            nameAr: 'معمل الميكاترونيكس والطباعة ثلاثية الأبعاد',
            type: 'lab',
            floorNumber: 1,
            floorName: 'Ground Floor',
            floorNameAr: 'الدور الأرضي',
            buildingId: 'eng-hall',
            areaSqm: 180,
            powerKw: 26.2,
            baselineKw: 28.0,
            powerBreakdown: { hvac: 9.8, lighting: 3.2, equipment: 12.4, standby: 0.8 },
            telemetry: {
              temperature: 23.1,
              humidity: 49,
              co2Ppm: 680,
              noiseDb: 58,
              lightLux: 520,
              occupancy: 22,
              capacity: 30,
              doorOpen: true,
            },
            controls: {
              thermostatSetpoint: 22.5,
              hvacMode: 'auto',
              fanSpeed: 'med',
              lightingLevel: 85,
              lightingMode: 'eco_sensor',
              socketPowerCut: false,
              ecoScheduleActive: true,
            },
            historyHourly: [
              { time: '08:00', actualKw: 12.0, baselineKw: 14.0 },
              { time: '10:00', actualKw: 24.0, baselineKw: 26.0 },
              { time: '12:00', actualKw: 28.1, baselineKw: 29.5 },
              { time: '14:00', actualKw: 26.2, baselineKw: 28.0 },
              { time: '16:00', actualKw: 19.5, baselineKw: 21.0 },
              { time: '18:00', actualKw: 9.0, baselineKw: 11.0 },
            ],
          },
          {
            id: 'eng-105',
            code: 'ENG-105',
            name: 'Auditorium Alpha (Grand Lecture Hall)',
            nameAr: 'مدرج ألفا الرئيسي للندوات والمحاضرات',
            type: 'auditorium',
            floorNumber: 1,
            floorName: 'Ground Floor',
            floorNameAr: 'الدور الأرضي',
            buildingId: 'eng-hall',
            areaSqm: 380,
            powerKw: 42.0,
            baselineKw: 55.0,
            powerBreakdown: { hvac: 28.0, lighting: 7.5, equipment: 5.5, standby: 1.0 },
            telemetry: {
              temperature: 22.0,
              humidity: 45,
              co2Ppm: 610,
              noiseDb: 35,
              lightLux: 350,
              occupancy: 180,
              capacity: 300,
              doorOpen: false,
            },
            controls: {
              thermostatSetpoint: 22.0,
              hvacMode: 'cool',
              fanSpeed: 'auto',
              lightingLevel: 60,
              lightingMode: 'schedule',
              socketPowerCut: false,
              ecoScheduleActive: true,
            },
            historyHourly: [
              { time: '08:00', actualKw: 15.0, baselineKw: 20.0 },
              { time: '10:00', actualKw: 45.0, baselineKw: 58.0 },
              { time: '12:00', actualKw: 48.0, baselineKw: 60.0 },
              { time: '14:00', actualKw: 42.0, baselineKw: 55.0 },
              { time: '16:00', actualKw: 22.0, baselineKw: 30.0 },
              { time: '18:00', actualKw: 8.0, baselineKw: 15.0 },
            ],
          },
        ],
      },
      {
        floorNumber: 2,
        name: 'Second Floor: Faculty Offices & Computer Science Studios',
        nameAr: 'الدور الثاني: مكاتب أعضاء هيئة التدريس ومختبرات البرمجيات',
        powerKw: 118,
        roomsCount: 8,
        rooms: [
          {
            id: 'eng-204',
            code: 'ENG-204',
            name: 'Cloud Computing & Distributed Systems Lab',
            nameAr: 'مختبر الحوسبة السحابية والأنظمة الموزعة',
            type: 'lab',
            floorNumber: 2,
            floorName: 'Second Floor',
            floorNameAr: 'الدور الثاني',
            buildingId: 'eng-hall',
            areaSqm: 110,
            powerKw: 15.8,
            baselineKw: 16.5,
            powerBreakdown: { hvac: 6.4, lighting: 1.6, equipment: 7.2, standby: 0.6 },
            telemetry: {
              temperature: 22.3,
              humidity: 44,
              co2Ppm: 520,
              noiseDb: 40,
              lightLux: 450,
              occupancy: 18,
              capacity: 28,
              doorOpen: false,
            },
            controls: {
              thermostatSetpoint: 22.5,
              hvacMode: 'cool',
              fanSpeed: 'low',
              lightingLevel: 70,
              lightingMode: 'eco_sensor',
              socketPowerCut: false,
              ecoScheduleActive: true,
            },
            historyHourly: [
              { time: '08:00', actualKw: 7.0, baselineKw: 8.5 },
              { time: '10:00', actualKw: 14.5, baselineKw: 15.0 },
              { time: '12:00', actualKw: 16.2, baselineKw: 17.0 },
              { time: '14:00', actualKw: 15.8, baselineKw: 16.5 },
              { time: '16:00', actualKw: 11.2, baselineKw: 13.0 },
              { time: '18:00', actualKw: 5.5, baselineKw: 7.0 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'sci-complex',
    code: 'SCI-02',
    name: 'Advanced Science & Bio-Research Complex',
    nameAr: 'مجمع العلوم المتقدمة والأبحاث الحيوية',
    zone: 'South Campus',
    zoneAr: 'المنطقة الجنوبية',
    areaSqm: 31200,
    floorsCount: 5,
    occupancyCurrent: 890,
    occupancyMax: 1200,
    currentPowerKw: 684,
    baselineKw: 620,
    solarRoofKw: 210,
    status: 'warning',
    eui: 158,
    hvacMode: 'Standard',
    hvacModeAr: 'الوضع التشغيلي القياسي',
    systemsBreakdown: { hvac: 54, lighting: 14, plugs: 18, specialized: 14 },
    temperatureAvg: 21.4,
    co2PpmAvg: 640,
    activeAlertsCount: 2,
    hourlyTrend: createHourlyTrend(660),
    floors: [
      {
        floorNumber: 1,
        name: 'Level 1: Genomics & Nanotech Cleanrooms',
        nameAr: 'المستوى 1: غرف أبحاث الجينوم والنانوتكنولوجي فائقة النقاء',
        powerKw: 245,
        roomsCount: 5,
        rooms: [
          {
            id: 'sci-101',
            code: 'SCI-101',
            name: 'ISO-Class 5 Nanofabrication Cleanroom',
            nameAr: 'غرفة النانو المعقمة فائقة النقاء (ISO-5)',
            type: 'lab',
            floorNumber: 1,
            floorName: 'Level 1',
            floorNameAr: 'المستوى 1',
            buildingId: 'sci-complex',
            areaSqm: 210,
            powerKw: 52.8,
            baselineKw: 44.0,
            powerBreakdown: { hvac: 32.5, lighting: 4.8, equipment: 14.5, standby: 1.0 },
            telemetry: {
              temperature: 20.2,
              humidity: 42,
              co2Ppm: 460,
              noiseDb: 62,
              lightLux: 750,
              occupancy: 8,
              capacity: 12,
              doorOpen: false,
            },
            controls: {
              thermostatSetpoint: 20.0,
              hvacMode: 'cool',
              fanSpeed: 'high',
              lightingLevel: 95,
              lightingMode: 'manual',
              socketPowerCut: false,
              ecoScheduleActive: false,
            },
            historyHourly: [
              { time: '08:00', actualKw: 42.0, baselineKw: 38.0 },
              { time: '10:00', actualKw: 51.5, baselineKw: 43.0 },
              { time: '12:00', actualKw: 55.0, baselineKw: 45.0 },
              { time: '14:00', actualKw: 52.8, baselineKw: 44.0 },
              { time: '16:00', actualKw: 49.0, baselineKw: 42.0 },
              { time: '18:00', actualKw: 45.0, baselineKw: 40.0 },
            ],
          },
          {
            id: 'sci-104',
            code: 'SCI-104',
            name: 'Cryogenic Electron Microscopy Suite',
            nameAr: 'مختبر الميكروسكوب الإلكتروني فائق التبريد',
            type: 'lab',
            floorNumber: 1,
            floorName: 'Level 1',
            floorNameAr: 'المستوى 1',
            buildingId: 'sci-complex',
            areaSqm: 120,
            powerKw: 38.4,
            baselineKw: 35.0,
            powerBreakdown: { hvac: 22.0, lighting: 2.4, equipment: 13.2, standby: 0.8 },
            telemetry: {
              temperature: 19.5,
              humidity: 38,
              co2Ppm: 430,
              noiseDb: 42,
              lightLux: 300,
              occupancy: 4,
              capacity: 8,
              doorOpen: false,
            },
            controls: {
              thermostatSetpoint: 19.5,
              hvacMode: 'cool',
              fanSpeed: 'med',
              lightingLevel: 50,
              lightingMode: 'manual',
              socketPowerCut: false,
              ecoScheduleActive: false,
            },
            historyHourly: [
              { time: '08:00', actualKw: 34.0, baselineKw: 34.0 },
              { time: '10:00', actualKw: 37.5, baselineKw: 35.0 },
              { time: '12:00', actualKw: 39.0, baselineKw: 36.0 },
              { time: '14:00', actualKw: 38.4, baselineKw: 35.0 },
              { time: '16:00', actualKw: 36.0, baselineKw: 34.0 },
              { time: '18:00', actualKw: 35.0, baselineKw: 34.0 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'cent-lib',
    code: 'LIB-03',
    name: 'Central University Digital Library',
    nameAr: 'المكتبة الرقمية المركزية',
    zone: 'Central Campus',
    zoneAr: 'المنطقة المركزية',
    areaSqm: 18900,
    floorsCount: 4,
    occupancyCurrent: 640,
    occupancyMax: 1100,
    currentPowerKw: 294,
    baselineKw: 340,
    solarRoofKw: 140,
    status: 'optimal',
    eui: 88,
    hvacMode: 'Eco-Setback',
    hvacModeAr: 'التحكم الذكي التوفيري',
    systemsBreakdown: { hvac: 42, lighting: 28, plugs: 24, specialized: 6 },
    temperatureAvg: 23.2,
    co2PpmAvg: 510,
    activeAlertsCount: 0,
    hourlyTrend: createHourlyTrend(310),
    floors: [
      {
        floorNumber: 2,
        name: 'Floor 2: Silent Study Commons & Digital Archives',
        nameAr: 'الدور الثاني: قاعة القراءة الصامتة والأرشيف الرقمي',
        powerKw: 78,
        roomsCount: 6,
        rooms: [
          {
            id: 'lib-201',
            code: 'LIB-201',
            name: 'Atrium Silent Reading Hall',
            nameAr: 'البهو المركزي للقراءة الصامتة',
            type: 'classroom',
            floorNumber: 2,
            floorName: 'Floor 2',
            floorNameAr: 'الدور الثاني',
            buildingId: 'cent-lib',
            areaSqm: 420,
            powerKw: 24.5,
            baselineKw: 32.0,
            powerBreakdown: { hvac: 12.5, lighting: 5.5, equipment: 6.0, standby: 0.5 },
            telemetry: {
              temperature: 22.9,
              humidity: 45,
              co2Ppm: 520,
              noiseDb: 28,
              lightLux: 510,
              occupancy: 112,
              capacity: 180,
              doorOpen: false,
            },
            controls: {
              thermostatSetpoint: 23.0,
              hvacMode: 'eco',
              fanSpeed: 'low',
              lightingLevel: 65,
              lightingMode: 'circadian',
              socketPowerCut: false,
              ecoScheduleActive: true,
            },
            historyHourly: [
              { time: '08:00', actualKw: 14.0, baselineKw: 20.0 },
              { time: '10:00', actualKw: 22.0, baselineKw: 28.0 },
              { time: '12:00', actualKw: 26.0, baselineKw: 34.0 },
              { time: '14:00', actualKw: 24.5, baselineKw: 32.0 },
              { time: '16:00', actualKw: 23.0, baselineKw: 30.0 },
              { time: '18:00', actualKw: 18.0, baselineKw: 24.0 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'innov-hub',
    code: 'INN-04',
    name: 'AI & Clean-Tech Innovation Hub',
    nameAr: 'مركز أبحاث الذكاء الاصطناعي وتقنيات الطاقة النظيفة',
    zone: 'Innovation Quad',
    zoneAr: 'واحة الابتكار التقني',
    areaSqm: 16500,
    floorsCount: 3,
    occupancyCurrent: 410,
    occupancyMax: 600,
    currentPowerKw: 412,
    baselineKw: 390,
    solarRoofKw: 185,
    status: 'warning',
    eui: 142,
    hvacMode: 'Peak-Shaving',
    hvacModeAr: 'تخفيف أحمال الذروة',
    systemsBreakdown: { hvac: 40, lighting: 12, plugs: 18, specialized: 30 },
    temperatureAvg: 22.1,
    co2PpmAvg: 610,
    activeAlertsCount: 2,
    hourlyTrend: createHourlyTrend(400),
    floors: [
      {
        floorNumber: 1,
        name: 'Ground Floor: HPC Data Center & Hardware Incubator',
        nameAr: 'الدور الأرضي: مركز الحوسبة الفائقة (HPC) وحاضنة العتاد',
        powerKw: 195,
        roomsCount: 4,
        rooms: [
          {
            id: 'inn-103',
            code: 'INN-103',
            name: 'Campus High Performance Computing (HPC) Server Core',
            nameAr: 'مركز الخوادم والحوسبة فائقة السرعة للجامعة',
            type: 'server_room',
            floorNumber: 1,
            floorName: 'Ground Floor',
            floorNameAr: 'الدور الأرضي',
            buildingId: 'innov-hub',
            areaSqm: 95,
            powerKw: 88.0,
            baselineKw: 78.0,
            powerBreakdown: { hvac: 38.0, lighting: 1.0, equipment: 48.0, standby: 1.0 },
            telemetry: {
              temperature: 24.8,
              humidity: 36,
              co2Ppm: 410,
              noiseDb: 72,
              lightLux: 200,
              occupancy: 2,
              capacity: 5,
              doorOpen: false,
            },
            controls: {
              thermostatSetpoint: 21.0,
              hvacMode: 'cool',
              fanSpeed: 'high',
              lightingLevel: 40,
              lightingMode: 'eco_sensor',
              socketPowerCut: false,
              ecoScheduleActive: false,
            },
            historyHourly: [
              { time: '08:00', actualKw: 76.0, baselineKw: 75.0 },
              { time: '10:00', actualKw: 84.0, baselineKw: 78.0 },
              { time: '12:00', actualKw: 92.0, baselineKw: 80.0 },
              { time: '14:00', actualKw: 88.0, baselineKw: 78.0 },
              { time: '16:00', actualKw: 86.0, baselineKw: 78.0 },
              { time: '18:00', actualKw: 82.0, baselineKw: 76.0 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'stud-union',
    code: 'STU-05',
    name: 'Student Activity Hub & Central Dining',
    nameAr: 'مبنى الأنشطة الطلابية والبهو المركزي',
    zone: 'Central Campus',
    zoneAr: 'المنطقة المركزية',
    areaSqm: 14200,
    floorsCount: 2,
    occupancyCurrent: 820,
    occupancyMax: 1400,
    currentPowerKw: 312,
    baselineKw: 380,
    solarRoofKw: 92,
    status: 'optimal',
    eui: 110,
    hvacMode: 'Standard',
    hvacModeAr: 'الوضع التشغيلي القياسي',
    systemsBreakdown: { hvac: 48, lighting: 20, plugs: 22, specialized: 10 },
    temperatureAvg: 23.5,
    co2PpmAvg: 720,
    activeAlertsCount: 1,
    hourlyTrend: createHourlyTrend(320),
    floors: [
      {
        floorNumber: 1,
        name: 'First Floor: Dining Commons & Event Hall',
        nameAr: 'الدور الأول: صالة المطاعم والفعاليات الكبرى',
        powerKw: 185,
        roomsCount: 4,
        rooms: [
          {
            id: 'stu-101',
            code: 'STU-101',
            name: 'Central Food Court & Eco-Dining',
            nameAr: 'ردهة المطاعم والخدمات الغذائية المستدامة',
            type: 'classroom',
            floorNumber: 1,
            floorName: 'First Floor',
            floorNameAr: 'الدور الأول',
            buildingId: 'stud-union',
            areaSqm: 560,
            powerKw: 74.0,
            baselineKw: 85.0,
            powerBreakdown: { hvac: 42.0, lighting: 12.0, equipment: 18.0, standby: 2.0 },
            telemetry: {
              temperature: 23.8,
              humidity: 52,
              co2Ppm: 780,
              noiseDb: 68,
              lightLux: 620,
              occupancy: 380,
              capacity: 550,
              doorOpen: true,
            },
            controls: {
              thermostatSetpoint: 23.0,
              hvacMode: 'cool',
              fanSpeed: 'med',
              lightingLevel: 80,
              lightingMode: 'circadian',
              socketPowerCut: false,
              ecoScheduleActive: true,
            },
            historyHourly: [
              { time: '08:00', actualKw: 28.0, baselineKw: 35.0 },
              { time: '10:00', actualKw: 48.0, baselineKw: 55.0 },
              { time: '12:00', actualKw: 88.0, baselineKw: 96.0 },
              { time: '14:00', actualKw: 74.0, baselineKw: 85.0 },
              { time: '16:00', actualKw: 42.0, baselineKw: 50.0 },
              { time: '18:00', actualKw: 32.0, baselineKw: 40.0 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'dorm-north',
    code: 'DRM-06',
    name: 'Smart Residential Complex North',
    nameAr: 'المجمع السكني الطلابي الذكي (شمال)',
    zone: 'North Campus',
    zoneAr: 'المنطقة الشمالية',
    areaSqm: 22000,
    floorsCount: 6,
    occupancyCurrent: 360,
    occupancyMax: 800,
    currentPowerKw: 280,
    baselineKw: 340,
    solarRoofKw: 110,
    status: 'optimal',
    eui: 74,
    hvacMode: 'Eco-Setback',
    hvacModeAr: 'التحكم الذكي التوفيري',
    systemsBreakdown: { hvac: 58, lighting: 16, plugs: 24, specialized: 2 },
    temperatureAvg: 23.0,
    co2PpmAvg: 480,
    activeAlertsCount: 0,
    hourlyTrend: createHourlyTrend(290),
    floors: [
      {
        floorNumber: 3,
        name: 'Floor 3: Living Quarters & Study Lounge',
        nameAr: 'الدور الثالث: الأجنحة السكنية وردهة المذاكرة المشتركة',
        powerKw: 42,
        roomsCount: 12,
        rooms: [
          {
            id: 'drm-302',
            code: 'DRM-302',
            name: 'Resident Study Suite 302',
            nameAr: 'قاعة المذاكرة المشتركة جناح 302',
            type: 'classroom',
            floorNumber: 3,
            floorName: 'Floor 3',
            floorNameAr: 'الدور الثالث',
            buildingId: 'dorm-north',
            areaSqm: 65,
            powerKw: 4.8,
            baselineKw: 6.5,
            powerBreakdown: { hvac: 2.8, lighting: 0.8, equipment: 1.0, standby: 0.2 },
            telemetry: {
              temperature: 22.8,
              humidity: 47,
              co2Ppm: 510,
              noiseDb: 32,
              lightLux: 420,
              occupancy: 6,
              capacity: 14,
              doorOpen: false,
            },
            controls: {
              thermostatSetpoint: 23.0,
              hvacMode: 'auto',
              fanSpeed: 'low',
              lightingLevel: 60,
              lightingMode: 'eco_sensor',
              socketPowerCut: false,
              ecoScheduleActive: true,
            },
            historyHourly: [
              { time: '08:00', actualKw: 2.1, baselineKw: 3.5 },
              { time: '10:00', actualKw: 3.8, baselineKw: 5.0 },
              { time: '12:00', actualKw: 4.2, baselineKw: 5.8 },
              { time: '14:00', actualKw: 4.8, baselineKw: 6.5 },
              { time: '16:00', actualKw: 5.4, baselineKw: 7.0 },
              { time: '18:00', actualKw: 6.2, baselineKw: 7.5 },
            ],
          },
        ],
      },
    ],
  },
];

export const initialAlerts: AlertItem[] = [
  {
    id: 'alt-001',
    title: 'HPC Server Core Thermal Over-Threshold',
    titleAr: 'تجاوز حد الحرارة الآمن في مركز الحوسبة الفائقة (HPC)',
    description: 'Chiller loop Delta-T degraded. Core ambient reached 24.8°C (threshold: 23.0°C). Power spike +14% over baseline.',
    descriptionAr: 'انخفاض كفاءة دورة التبريد في مركز الخوادم. درجة الحرارة وصلت إلى 24.8 مئوية (الحد المسموح 23 مئوية) مع زيادة 14% في الاستهلاك.',
    severity: 'critical',
    category: 'hvac',
    buildingId: 'innov-hub',
    buildingName: 'AI & Clean-Tech Innovation Hub',
    buildingNameAr: 'مركز أبحاث الذكاء الاصطناعي',
    roomId: 'inn-103',
    roomName: 'Campus High Performance Computing (HPC) Server Core',
    roomNameAr: 'مركز الخوادم والحوسبة فائقة السرعة',
    timestamp: '14:28 (12 mins ago)',
    timestampAr: '14:28 (منذ 12 دقيقة)',
    status: 'active',
    potentialSavingsKwh: 120,
    suggestedAction: 'Throttle secondary GPU nodes or switch backup secondary chiller loop',
    suggestedActionAr: 'خفض حمل المعالجات الرسومية الثانوية أو تحويل دورة التبريد الاحتياطية',
  },
  {
    id: 'alt-002',
    title: 'Cleanroom ISO-5 HVAC Over-consumption',
    titleAr: 'استهلاك غير اعتيادي لمكيفات غرفة النانو فائقة النقاء',
    description: 'Continuous cooling load at 32.5 kW despite external temperature cooling down. Possible air seal bypass.',
    descriptionAr: 'استهلاك تبريد مستمر بقدرة 32.5 كيلوواط بالرغم من انخفاض درجات الحرارة الخارجية، اشتباه في تسريب عزل الهواء.',
    severity: 'critical',
    category: 'hvac',
    buildingId: 'sci-complex',
    buildingName: 'Advanced Science & Bio-Research Complex',
    buildingNameAr: 'مجمع العلوم المتقدمة والأبحاث الحيوية',
    roomId: 'sci-101',
    roomName: 'ISO-Class 5 Nanofabrication Cleanroom',
    roomNameAr: 'غرفة النانو المعقمة فائقة النقاء (ISO-5)',
    timestamp: '13:50 (50 mins ago)',
    timestampAr: '13:50 (منذ 50 دقيقة)',
    status: 'active',
    potentialSavingsKwh: 160,
    suggestedAction: 'Inspect HEPA filter differential pressure and pressurization dampers',
    suggestedActionAr: 'فحص فلاتر هيبا وضغط الهواء وصمامات العزل',
  },
  {
    id: 'alt-003',
    title: 'Solar String Inverter 4 Communication Lag',
    titleAr: 'تأخر استجابة عاكس الطاقة الشمسية رقم 4 في كلية الهندسة',
    description: 'Rooftop array generating 22 kW less than sister array under equal 840 W/m² irradiance.',
    descriptionAr: 'الألواح الشمسية بسطح كلية الهندسة تسجل إنتاجية أقل بـ 22 كيلوواط مقارنة بالمصفوفة المجاورة بنفس معدل الإشعاع.',
    severity: 'warning',
    category: 'solar',
    buildingId: 'eng-hall',
    buildingName: 'College of Engineering & Technology',
    buildingNameAr: 'كلية الهندسة والتقنية',
    timestamp: '12:15 (2 hrs ago)',
    timestampAr: '12:15 (منذ ساعتين)',
    status: 'active',
    potentialSavingsKwh: 85,
    suggestedAction: 'Clean dust on String 4B panels and restart telemetry gateway',
    suggestedActionAr: 'تنظيف الغبار عن مصفوفة 4B وإعادة تشغيل بوابة الاتصال',
  },
  {
    id: 'alt-004',
    title: 'Bio-Complex Level 1 Door Left Ajar',
    titleAr: 'باب معمل الميكروسكوب مفتوح مما يسبب هدر التبريد',
    description: 'Magnetic door contact active for 38 minutes. Negative pressure compensation causing fan overload.',
    descriptionAr: 'حساس الباب المغناطيسي يسجل فتح الباب لمدة 38 دقيقة متواصلة مما يرفع حمل مراوح الشفط.',
    severity: 'warning',
    category: 'occupancy',
    buildingId: 'sci-complex',
    buildingName: 'Advanced Science & Bio-Research Complex',
    buildingNameAr: 'مجمع العلوم المتقدمة والأبحاث الحيوية',
    roomId: 'sci-104',
    roomName: 'Cryogenic Electron Microscopy Suite',
    roomNameAr: 'مختبر الميكروسكوب الإلكتروني فائق التبريد',
    timestamp: '14:02 (38 mins ago)',
    timestampAr: '14:02 (منذ 38 دقيقة)',
    status: 'active',
    potentialSavingsKwh: 35,
    suggestedAction: 'Issue automated alert tone to lab occupants to seal vestibule door',
    suggestedActionAr: 'إصدار تنبيه صوتي لشاغلي المعمل لإغلاق الباب العازل',
  },
  {
    id: 'alt-005',
    title: 'High Standby Load During Inactive Hours',
    titleAr: 'استهلاك وضع الاستعداد مرتفع في ورشة التصنيع 3D',
    description: 'Heated beds on idle 3D printers drawing 3.8 kW continuous power while room is vacant.',
    descriptionAr: 'سخانات الطابعات ثلاثية الأبعاد تسحب 3.8 كيلوواط بشكل متواصل دون وجود طلاب في الغرفة.',
    severity: 'warning',
    category: 'electrical',
    buildingId: 'eng-hall',
    buildingName: 'College of Engineering & Technology',
    buildingNameAr: 'كلية الهندسة والتقنية',
    roomId: 'eng-102',
    roomName: 'Mechatronics & 3D Fabrication Suite',
    roomNameAr: 'معمل الميكاترونيكس والطباعة ثلاثية الأبعاد',
    timestamp: '11:40 (3 hrs ago)',
    timestampAr: '11:40 (منذ 3 ساعات)',
    status: 'acknowledged',
    potentialSavingsKwh: 28,
    suggestedAction: 'Trigger remote smart socket cut-off for idle fabrication bench',
    suggestedActionAr: 'تفعيل فصل المقابس الذكية عن بُعد لمنصات الطباعة الخاملة',
  },
  {
    id: 'alt-006',
    title: 'Peak Shaving Automated Eco-Dispatch Initiated',
    titleAr: 'تفعيل بروتوكول تخفيف أحمال الذروة تلقائياً في واحة الابتكار',
    description: 'Building demand reached 412 kW. Chilled water temperature reset by +1.0°C to avert peak utility tariff.',
    descriptionAr: 'تجاوز حمل المبنى 412 كيلوواط. تم رفع حرارة المياه المبردة بدرجة واحدة لتفادي تعريفة الذروة.',
    severity: 'info',
    category: 'hvac',
    buildingId: 'innov-hub',
    buildingName: 'AI & Clean-Tech Innovation Hub',
    buildingNameAr: 'مركز أبحاث الذكاء الاصطناعي',
    timestamp: '13:00 (1.5 hrs ago)',
    timestampAr: '13:00 (منذ ساعة ونصف)',
    status: 'active',
    potentialSavingsKwh: 90,
    suggestedAction: 'Monitor student occupancy levels during peak 13:00-15:00 window',
    suggestedActionAr: 'متابعة نسب الإشغال خلال فترة الذروة بين 13:00 و 15:00',
  },
];
